language: objective-c

osx_image: xcode7.3
xcode_project: Structure.xcodeproj

xcode_scheme:
        - Structure iOS
        - Structure Mac
        - Structure tvOS

xcode_sdk:
        - iphonesimulator9.3
        - macosx10.11
        - appletvsimulator9.2

matrix:
        exclude:
                - xcode_scheme: Structure iOS
                  xcode_sdk: macosx10.11
                - xcode_scheme: Structure iOS
                  xcode_sdk: appletvsimulator9.2
                - xcode_scheme: Structure Mac
                  xcode_sdk: iphonesimulator9.3
                - xcode_scheme: Structure Mac
                  xcode_sdk: appletvsimulator9.2
                - xcode_scheme: Structure tvOS
                  xcode_sdk: iphonesimulator9.3
                - xcode_scheme: Structure tvOS
                  xcode_sdk: macosx10.11
