language: objective-c

branches:
  only:
    - master

osx_image: xcode7.3
xcode_project: Structure.xcodeproj

xcode_scheme:
        - Structure iOS
        - Structure Mac
        - Structure tvOS

xcode_sdk:
        - iphonesimulator9.3
        - macosx10.11
        - tvOS9.2

