language: objective-c

branches:
  only:
    - master

xcode_project: Structure.xcodeproj
xcode_scheme: Structure iOS Tests
osx_image: xcode7.3
xcode_sdk: iphonesimulator9.3

script:
  - xcodebuild test -project Structure.xcodeproj -scheme "Structure iOS" -destination "platform=iOS Simulator,name=iPhone 6s"

